version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install -g serverless@1.41.1
      - npm install hapi jsonpath-plus
  build:
    commands:
      - serverless deploy