service: hastify
plugins:
  - serverless-offline
  - serverless-python-requirements
provider:
  name: aws
  runtime: python3.7
  region: eu-west-1
  stage: prod
functions:
  getURL:
    handler: handlers/auth.getauthurl
    events:
      - http:
          path: /authurl
          method: get
  getaccesstoken:
    handler: handlers/access.getaccesstoken
    events:
      - http:
          path: /access
          method: post
          cors: true
  createmix:
    handler: handlers/mix.createmix
    events:
      - http:
          path: /mix
          method: post
          cors: true
  genreseeds:
    handler: handlers/genre.genreseeds
    events:
      - http:
          path: /genres
          method: post
          cors: true
  createplaylist:
    handler: handlers/playlist.createplaylist
    events:
      - http:
          path: /playlist
          method: post
          cors: true
  addtracks:
    handler: handlers/tracks.addtracks
    events:
      - http:
          path: /tracks
          method: post
          cors: true
  custom:
    pythonRequirements:
      dockerizePip: non-linux