service: spotipy-test
plugins:
  - serverless-offline
provider:
  name: aws
  runtime: python3.7
functions:
  getURL:
    handler: handlers/auth.getauthurl
    events:
      - http:
          path: /authurl
          method: get
  getaccesstoken:
    handler: handlers/access.getaccesstoken
    events:
      - http:
          path: /access
          method: post
          cors: true
  createmix:
    handler: handlers/mix.createmix
    events:
      - http:
          path: /mix
          method: post
          cors: true
  genreseeds:
    handler: handlers/genre.genreseeds
    events:
      - http:
          path: /genres
          method: post
          cors: true